server:
  port: 8080
  servlet:
    context-path: /kvgh
spring:
#  mvc:
#    static-path-pattern: /static/**
#  thymeleaf:
#    cache: true
#    encoding: UTF-8
#    prefix: classpath:/templates/
#    suffix: .html
#    servlet:
#      content-type: text/html
#    mode: LEGACYHTML5 # 将可以使用不太严格的HTML语法
  datasource:
    platform: mysql
    url: jdbc:mysql://127.0.0.1/kvgh1?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Rhs$1234
    sql-script-encoding: UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  flyway:
    enabled: true
    baselineOnMigrate: true
excel:
  path: C:/vhlc/excel/
license:
  app-name: Kvgh
  app-version: v1.1
  mac-address: xx-xx-xx-xx-xx-xx
  file: Kvgh-v1.1-20200331.dqlf
#logging:
  #level:
    # root: INFO
    # com.cisco.gdc: INFO
    # com.cisco.gdc.cmms.service.web: DEBUG
kvgh:
  branch:
    taxid: 92505506
